apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-app
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 5
      parallelism: 2
      template:
        metadata:
           name:  cron-app
        spec:
          containers:
          - name: job
            image: alpine:latest
            command: ["/bin/sh", "-c"]
            args: ["echo running job from $HOSTNAME!"]
          restartPolicy: Never
