apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app_name: nginx
      env: dev
  template:
    metadata:
      labels:
        app_name: nginx
        env: dev
    spec:
      nodeSelector: 
        nodeType: health
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
      
