apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: nginx-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app_name: nginx
      env: dev
  template:
    metadata:
      labels:
        app_name: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
